
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sap.xi.a1s.global;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-18T14:25:31.310-03:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "service",
                      portName = "binding_SOAP12",
                      targetNamespace = "http://sap.com/xi/A1S/Global",
                      wsdlLocation = "file:/media/claudio/claudio-ssd/Dev/workspaces/partners/teste-cxf/WebContent/WEB-INF/wsdl/c4c_wsdl_salesorder.wsdl",
                      endpointInterface = "com.sap.xi.a1s.global.CustomerOrderProcessingManageCustomerOrderIn")
                      
public class Binding_SOAP12Impl implements CustomerOrderProcessingManageCustomerOrderIn {

    private static final Logger LOG = Logger.getLogger(Binding_SOAP12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.sap.xi.a1s.global.CustomerOrderProcessingManageCustomerOrderIn#maintainBundle(com.sap.xi.a1s.global.CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderBundleMaintainRequestSyncV1)*
     */
    public com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 maintainBundle(CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderBundleMaintainRequestSyncV1) throws StandardFaultMessage   { 
        LOG.info("Executing operation maintainBundle");
        System.out.println(customerOrderBundleMaintainRequestSyncV1);
        try {
            com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 _return = new com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1();
            java.util.List<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation> _returnCustomerOrder = new java.util.ArrayList<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation>();
            com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation _returnCustomerOrderVal1 = new com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation();
            _returnCustomerOrderVal1.setChangeStateID("ChangeStateID101477078");
            _returnCustomerOrderVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID1456064530");
            com.sap.xi.ap.common.gdt.UUID _returnCustomerOrderVal1UUID = new com.sap.xi.ap.common.gdt.UUID();
            _returnCustomerOrderVal1UUID.setValue("Value-1118126362");
            _returnCustomerOrderVal1UUID.setSchemeID("SchemeID-616339975");
            _returnCustomerOrderVal1UUID.setSchemeAgencyID("SchemeAgencyID-287364620");
            _returnCustomerOrderVal1.setUUID(_returnCustomerOrderVal1UUID);
            com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID _returnCustomerOrderVal1ID = new com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID();
            _returnCustomerOrderVal1ID.setValue("Value-917837555");
            _returnCustomerOrderVal1ID.setSchemeID("SchemeID969804795");
            _returnCustomerOrderVal1ID.setSchemeAgencyID("SchemeAgencyID2125133319");
            _returnCustomerOrderVal1ID.setSchemeAgencySchemeAgencyID("SchemeAgencySchemeAgencyID203604377");
            _returnCustomerOrderVal1.setID(_returnCustomerOrderVal1ID);
            _returnCustomerOrder.add(_returnCustomerOrderVal1);
            _return.getCustomerOrder().addAll(_returnCustomerOrder);
            com.sap.xi.ap.common.gdt.Log _returnLog = new com.sap.xi.ap.common.gdt.Log();
            _returnLog.setBusinessDocumentProcessingResultCode("BusinessDocumentProcessingResultCode-1947941107");
            _returnLog.setMaximumLogItemSeverityCode("MaximumLogItemSeverityCode-1052234854");
            java.util.List<com.sap.xi.ap.common.gdt.LogItem> _returnLogItem = new java.util.ArrayList<com.sap.xi.ap.common.gdt.LogItem>();
            com.sap.xi.ap.common.gdt.LogItem _returnLogItemVal1 = new com.sap.xi.ap.common.gdt.LogItem();
            _returnLogItemVal1.setTypeID("TypeID-1478454320");
            com.sap.xi.ap.common.gdt.LogItemCategoryCode _returnLogItemVal1CategoryCode = new com.sap.xi.ap.common.gdt.LogItemCategoryCode();
            _returnLogItemVal1CategoryCode.setValue("Value141533558");
            _returnLogItemVal1CategoryCode.setListID("ListID-321543675");
            _returnLogItemVal1CategoryCode.setListVersionID("ListVersionID-511749048");
            _returnLogItemVal1CategoryCode.setListAgencyID("ListAgencyID1543080209");
            _returnLogItemVal1CategoryCode.setListAgencySchemeID("ListAgencySchemeID1533196051");
            _returnLogItemVal1CategoryCode.setListAgencySchemeAgencyID("ListAgencySchemeAgencyID2051256850");
            _returnLogItemVal1.setCategoryCode(_returnLogItemVal1CategoryCode);
            _returnLogItemVal1.setSeverityCode("SeverityCode-173817266");
            _returnLogItemVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID-650549829");
            _returnLogItemVal1.setReferenceMessageElementName("ReferenceMessageElementName878128132");
            _returnLogItemVal1.setNote("Note1143331737");
            _returnLogItemVal1.setNoteTemplateText("NoteTemplateText-1854094571");
            com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList _returnLogItemVal1LogItemNotePlaceholderSubstitutionList = new com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList();
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderID("FirstPlaceholderID-1811068238");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderID("SecondPlaceholderID-616475814");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderID("ThirdPlaceholderID1237385644");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderID("FourthPlaceholderID1677369783");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderSubstitutionText("FirstPlaceholderSubstitutionText975871185");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderSubstitutionText("SecondPlaceholderSubstitutionText424049244");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderSubstitutionText("ThirdPlaceholderSubstitutionText-440558927");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderSubstitutionText("FourthPlaceholderSubstitutionText-551401263");
            _returnLogItemVal1.setLogItemNotePlaceholderSubstitutionList(_returnLogItemVal1LogItemNotePlaceholderSubstitutionList);
            _returnLogItemVal1.setWebURI("WebURI-323525583");
            _returnLogItem.add(_returnLogItemVal1);
            _returnLog.getItem().addAll(_returnLogItem);
            _return.setLog(_returnLog);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StandardFaultMessage("StandardFaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.sap.xi.a1s.global.CustomerOrderProcessingManageCustomerOrderIn#checkMaintainBundle(com.sap.xi.a1s.global.CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderRequestBundleCheckRequestSyncV1)*
     */
    public com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 checkMaintainBundle(CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderRequestBundleCheckRequestSyncV1) throws StandardFaultMessage   { 
        LOG.info("Executing operation checkMaintainBundle");
        System.out.println(customerOrderRequestBundleCheckRequestSyncV1);
        try {
            com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 _return = new com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1();
            java.util.List<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation> _returnCustomerOrder = new java.util.ArrayList<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation>();
            com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation _returnCustomerOrderVal1 = new com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation();
            _returnCustomerOrderVal1.setChangeStateID("ChangeStateID204771447");
            _returnCustomerOrderVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID-974165179");
            com.sap.xi.ap.common.gdt.UUID _returnCustomerOrderVal1UUID = new com.sap.xi.ap.common.gdt.UUID();
            _returnCustomerOrderVal1UUID.setValue("Value741387678");
            _returnCustomerOrderVal1UUID.setSchemeID("SchemeID335731627");
            _returnCustomerOrderVal1UUID.setSchemeAgencyID("SchemeAgencyID-491267470");
            _returnCustomerOrderVal1.setUUID(_returnCustomerOrderVal1UUID);
            com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID _returnCustomerOrderVal1ID = new com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID();
            _returnCustomerOrderVal1ID.setValue("Value-1725723811");
            _returnCustomerOrderVal1ID.setSchemeID("SchemeID975263809");
            _returnCustomerOrderVal1ID.setSchemeAgencyID("SchemeAgencyID-222759782");
            _returnCustomerOrderVal1ID.setSchemeAgencySchemeAgencyID("SchemeAgencySchemeAgencyID1113335013");
            _returnCustomerOrderVal1.setID(_returnCustomerOrderVal1ID);
            _returnCustomerOrder.add(_returnCustomerOrderVal1);
            _return.getCustomerOrder().addAll(_returnCustomerOrder);
            com.sap.xi.ap.common.gdt.Log _returnLog = new com.sap.xi.ap.common.gdt.Log();
            _returnLog.setBusinessDocumentProcessingResultCode("BusinessDocumentProcessingResultCode-1410917970");
            _returnLog.setMaximumLogItemSeverityCode("MaximumLogItemSeverityCode463773025");
            java.util.List<com.sap.xi.ap.common.gdt.LogItem> _returnLogItem = new java.util.ArrayList<com.sap.xi.ap.common.gdt.LogItem>();
            com.sap.xi.ap.common.gdt.LogItem _returnLogItemVal1 = new com.sap.xi.ap.common.gdt.LogItem();
            _returnLogItemVal1.setTypeID("TypeID1273221861");
            com.sap.xi.ap.common.gdt.LogItemCategoryCode _returnLogItemVal1CategoryCode = new com.sap.xi.ap.common.gdt.LogItemCategoryCode();
            _returnLogItemVal1CategoryCode.setValue("Value390736363");
            _returnLogItemVal1CategoryCode.setListID("ListID1601913167");
            _returnLogItemVal1CategoryCode.setListVersionID("ListVersionID1430740219");
            _returnLogItemVal1CategoryCode.setListAgencyID("ListAgencyID582649148");
            _returnLogItemVal1CategoryCode.setListAgencySchemeID("ListAgencySchemeID-813097450");
            _returnLogItemVal1CategoryCode.setListAgencySchemeAgencyID("ListAgencySchemeAgencyID-766413413");
            _returnLogItemVal1.setCategoryCode(_returnLogItemVal1CategoryCode);
            _returnLogItemVal1.setSeverityCode("SeverityCode643258994");
            _returnLogItemVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID1970044321");
            _returnLogItemVal1.setReferenceMessageElementName("ReferenceMessageElementName1134008483");
            _returnLogItemVal1.setNote("Note1907689563");
            _returnLogItemVal1.setNoteTemplateText("NoteTemplateText-1943240214");
            com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList _returnLogItemVal1LogItemNotePlaceholderSubstitutionList = new com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList();
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderID("FirstPlaceholderID957189673");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderID("SecondPlaceholderID-72463634");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderID("ThirdPlaceholderID519405093");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderID("FourthPlaceholderID-1590645033");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderSubstitutionText("FirstPlaceholderSubstitutionText884895235");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderSubstitutionText("SecondPlaceholderSubstitutionText-13485272");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderSubstitutionText("ThirdPlaceholderSubstitutionText1505182974");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderSubstitutionText("FourthPlaceholderSubstitutionText-1132148784");
            _returnLogItemVal1.setLogItemNotePlaceholderSubstitutionList(_returnLogItemVal1LogItemNotePlaceholderSubstitutionList);
            _returnLogItemVal1.setWebURI("WebURI1365904057");
            _returnLogItem.add(_returnLogItemVal1);
            _returnLog.getItem().addAll(_returnLogItem);
            _return.setLog(_returnLog);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StandardFaultMessage("StandardFaultMessage...");
    }

}
