
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sap.xi.a1s.global;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-18T14:25:31.278-03:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "service",
                      portName = "binding",
                      targetNamespace = "http://sap.com/xi/A1S/Global",
                      wsdlLocation = "file:/media/claudio/claudio-ssd/Dev/workspaces/partners/teste-cxf/WebContent/WEB-INF/wsdl/c4c_wsdl_salesorder.wsdl",
                      endpointInterface = "com.sap.xi.a1s.global.CustomerOrderProcessingManageCustomerOrderIn")
                      
public class BindingImpl implements CustomerOrderProcessingManageCustomerOrderIn {

    private static final Logger LOG = Logger.getLogger(BindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sap.xi.a1s.global.CustomerOrderProcessingManageCustomerOrderIn#maintainBundle(com.sap.xi.a1s.global.CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderBundleMaintainRequestSyncV1)*
     */
    public com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 maintainBundle(CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderBundleMaintainRequestSyncV1) throws StandardFaultMessage   { 
        LOG.info("Executing operation maintainBundle");
        System.out.println(customerOrderBundleMaintainRequestSyncV1);
        try {
            com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 _return = new com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1();
            java.util.List<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation> _returnCustomerOrder = new java.util.ArrayList<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation>();
            com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation _returnCustomerOrderVal1 = new com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation();
            _returnCustomerOrderVal1.setChangeStateID("ChangeStateID-1198004862");
            _returnCustomerOrderVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID-553946119");
            com.sap.xi.ap.common.gdt.UUID _returnCustomerOrderVal1UUID = new com.sap.xi.ap.common.gdt.UUID();
            _returnCustomerOrderVal1UUID.setValue("Value888687569");
            _returnCustomerOrderVal1UUID.setSchemeID("SchemeID1755107457");
            _returnCustomerOrderVal1UUID.setSchemeAgencyID("SchemeAgencyID-18093253");
            _returnCustomerOrderVal1.setUUID(_returnCustomerOrderVal1UUID);
            com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID _returnCustomerOrderVal1ID = new com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID();
            _returnCustomerOrderVal1ID.setValue("Value-1180560956");
            _returnCustomerOrderVal1ID.setSchemeID("SchemeID-2021383305");
            _returnCustomerOrderVal1ID.setSchemeAgencyID("SchemeAgencyID-225758128");
            _returnCustomerOrderVal1ID.setSchemeAgencySchemeAgencyID("SchemeAgencySchemeAgencyID-1364293621");
            _returnCustomerOrderVal1.setID(_returnCustomerOrderVal1ID);
            _returnCustomerOrder.add(_returnCustomerOrderVal1);
            _return.getCustomerOrder().addAll(_returnCustomerOrder);
            com.sap.xi.ap.common.gdt.Log _returnLog = new com.sap.xi.ap.common.gdt.Log();
            _returnLog.setBusinessDocumentProcessingResultCode("BusinessDocumentProcessingResultCode-1548169253");
            _returnLog.setMaximumLogItemSeverityCode("MaximumLogItemSeverityCode1596164533");
            java.util.List<com.sap.xi.ap.common.gdt.LogItem> _returnLogItem = new java.util.ArrayList<com.sap.xi.ap.common.gdt.LogItem>();
            com.sap.xi.ap.common.gdt.LogItem _returnLogItemVal1 = new com.sap.xi.ap.common.gdt.LogItem();
            _returnLogItemVal1.setTypeID("TypeID-1796723769");
            com.sap.xi.ap.common.gdt.LogItemCategoryCode _returnLogItemVal1CategoryCode = new com.sap.xi.ap.common.gdt.LogItemCategoryCode();
            _returnLogItemVal1CategoryCode.setValue("Value1205079501");
            _returnLogItemVal1CategoryCode.setListID("ListID-111099152");
            _returnLogItemVal1CategoryCode.setListVersionID("ListVersionID596783386");
            _returnLogItemVal1CategoryCode.setListAgencyID("ListAgencyID-643720768");
            _returnLogItemVal1CategoryCode.setListAgencySchemeID("ListAgencySchemeID-644758794");
            _returnLogItemVal1CategoryCode.setListAgencySchemeAgencyID("ListAgencySchemeAgencyID1444022168");
            _returnLogItemVal1.setCategoryCode(_returnLogItemVal1CategoryCode);
            _returnLogItemVal1.setSeverityCode("SeverityCode-1720318276");
            _returnLogItemVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID-2030134008");
            _returnLogItemVal1.setReferenceMessageElementName("ReferenceMessageElementName703614149");
            _returnLogItemVal1.setNote("Note-112348554");
            _returnLogItemVal1.setNoteTemplateText("NoteTemplateText957532559");
            com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList _returnLogItemVal1LogItemNotePlaceholderSubstitutionList = new com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList();
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderID("FirstPlaceholderID1031567135");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderID("SecondPlaceholderID417204409");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderID("ThirdPlaceholderID-2135155048");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderID("FourthPlaceholderID-1546697990");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderSubstitutionText("FirstPlaceholderSubstitutionText-1295213765");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderSubstitutionText("SecondPlaceholderSubstitutionText1334380867");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderSubstitutionText("ThirdPlaceholderSubstitutionText2021080608");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderSubstitutionText("FourthPlaceholderSubstitutionText1736242343");
            _returnLogItemVal1.setLogItemNotePlaceholderSubstitutionList(_returnLogItemVal1LogItemNotePlaceholderSubstitutionList);
            _returnLogItemVal1.setWebURI("WebURI1425418642");
            _returnLogItem.add(_returnLogItemVal1);
            _returnLog.getItem().addAll(_returnLogItem);
            _return.setLog(_returnLog);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StandardFaultMessage("StandardFaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.sap.xi.a1s.global.CustomerOrderProcessingManageCustomerOrderIn#checkMaintainBundle(com.sap.xi.a1s.global.CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderRequestBundleCheckRequestSyncV1)*
     */
    public com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 checkMaintainBundle(CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderRequestBundleCheckRequestSyncV1) throws StandardFaultMessage   { 
        LOG.info("Executing operation checkMaintainBundle");
        System.out.println(customerOrderRequestBundleCheckRequestSyncV1);
        try {
            com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1 _return = new com.sap.xi.a1s.global.CustomerOrderMaintainConfirmationBundleMessageSyncV1();
            java.util.List<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation> _returnCustomerOrder = new java.util.ArrayList<com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation>();
            com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation _returnCustomerOrderVal1 = new com.sap.xi.a1s.global.CustomerOrderMaintainBundleConfirmation();
            _returnCustomerOrderVal1.setChangeStateID("ChangeStateID1695525309");
            _returnCustomerOrderVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID-1676226266");
            com.sap.xi.ap.common.gdt.UUID _returnCustomerOrderVal1UUID = new com.sap.xi.ap.common.gdt.UUID();
            _returnCustomerOrderVal1UUID.setValue("Value-66302054");
            _returnCustomerOrderVal1UUID.setSchemeID("SchemeID1476221657");
            _returnCustomerOrderVal1UUID.setSchemeAgencyID("SchemeAgencyID-1357779558");
            _returnCustomerOrderVal1.setUUID(_returnCustomerOrderVal1UUID);
            com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID _returnCustomerOrderVal1ID = new com.sap.xi.ap.common.gdt.BusinessTransactionDocumentID();
            _returnCustomerOrderVal1ID.setValue("Value470722269");
            _returnCustomerOrderVal1ID.setSchemeID("SchemeID1080346757");
            _returnCustomerOrderVal1ID.setSchemeAgencyID("SchemeAgencyID-1785225209");
            _returnCustomerOrderVal1ID.setSchemeAgencySchemeAgencyID("SchemeAgencySchemeAgencyID-1768087843");
            _returnCustomerOrderVal1.setID(_returnCustomerOrderVal1ID);
            _returnCustomerOrder.add(_returnCustomerOrderVal1);
            _return.getCustomerOrder().addAll(_returnCustomerOrder);
            com.sap.xi.ap.common.gdt.Log _returnLog = new com.sap.xi.ap.common.gdt.Log();
            _returnLog.setBusinessDocumentProcessingResultCode("BusinessDocumentProcessingResultCode558714100");
            _returnLog.setMaximumLogItemSeverityCode("MaximumLogItemSeverityCode2126077273");
            java.util.List<com.sap.xi.ap.common.gdt.LogItem> _returnLogItem = new java.util.ArrayList<com.sap.xi.ap.common.gdt.LogItem>();
            com.sap.xi.ap.common.gdt.LogItem _returnLogItemVal1 = new com.sap.xi.ap.common.gdt.LogItem();
            _returnLogItemVal1.setTypeID("TypeID-778339746");
            com.sap.xi.ap.common.gdt.LogItemCategoryCode _returnLogItemVal1CategoryCode = new com.sap.xi.ap.common.gdt.LogItemCategoryCode();
            _returnLogItemVal1CategoryCode.setValue("Value-745644081");
            _returnLogItemVal1CategoryCode.setListID("ListID252432702");
            _returnLogItemVal1CategoryCode.setListVersionID("ListVersionID-718839776");
            _returnLogItemVal1CategoryCode.setListAgencyID("ListAgencyID-1018736725");
            _returnLogItemVal1CategoryCode.setListAgencySchemeID("ListAgencySchemeID-1457511445");
            _returnLogItemVal1CategoryCode.setListAgencySchemeAgencyID("ListAgencySchemeAgencyID2124773780");
            _returnLogItemVal1.setCategoryCode(_returnLogItemVal1CategoryCode);
            _returnLogItemVal1.setSeverityCode("SeverityCode2113313545");
            _returnLogItemVal1.setReferenceObjectNodeSenderTechnicalID("ReferenceObjectNodeSenderTechnicalID325762763");
            _returnLogItemVal1.setReferenceMessageElementName("ReferenceMessageElementName-1591622627");
            _returnLogItemVal1.setNote("Note-1655138822");
            _returnLogItemVal1.setNoteTemplateText("NoteTemplateText-391175740");
            com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList _returnLogItemVal1LogItemNotePlaceholderSubstitutionList = new com.sap.xi.ap.common.gdt.LogItemNotePlaceholderSubstitutionList();
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderID("FirstPlaceholderID1983002737");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderID("SecondPlaceholderID1066902059");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderID("ThirdPlaceholderID-834678528");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderID("FourthPlaceholderID-2085985264");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFirstPlaceholderSubstitutionText("FirstPlaceholderSubstitutionText1292689447");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setSecondPlaceholderSubstitutionText("SecondPlaceholderSubstitutionText1635094387");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setThirdPlaceholderSubstitutionText("ThirdPlaceholderSubstitutionText1038459498");
            _returnLogItemVal1LogItemNotePlaceholderSubstitutionList.setFourthPlaceholderSubstitutionText("FourthPlaceholderSubstitutionText-234203759");
            _returnLogItemVal1.setLogItemNotePlaceholderSubstitutionList(_returnLogItemVal1LogItemNotePlaceholderSubstitutionList);
            _returnLogItemVal1.setWebURI("WebURI1042348434");
            _returnLogItem.add(_returnLogItemVal1);
            _returnLog.getItem().addAll(_returnLogItem);
            _return.setLog(_returnLog);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StandardFaultMessage("StandardFaultMessage...");
    }

}
