package com.sap.xi.a1s.global;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * 
 * 										
 *
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-18T14:25:31.331-03:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "CustomerOrderProcessingManageCustomerOrderIn")
@XmlSeeAlso({com.sap.xi.sapglobal20.global.ObjectFactory.class, com.sap.xi.ap.common.gdt.ObjectFactory.class, com.sap.xi.documentservices.global.ObjectFactory.class, com.sap.xi.basis.global.ObjectFactory.class, ObjectFactory.class, com.sap.xi.ap.common.global.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerOrderProcessingManageCustomerOrderIn {

    @WebMethod(operationName = "MaintainBundle", action = "http://sap.com/xi/A1S/Global/CustomerOrderProcessingManageCustomerOrderIn/MaintainBundleRequest")
    @WebResult(name = "CustomerOrderBundleMaintainConfirmation_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerOrderBundleMaintainConfirmation_sync_V1")
    public CustomerOrderMaintainConfirmationBundleMessageSyncV1 maintainBundle(
        @WebParam(partName = "CustomerOrderBundleMaintainRequest_sync_V1", name = "CustomerOrderBundleMaintainRequest_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderBundleMaintainRequestSyncV1
    ) throws StandardFaultMessage;

    @WebMethod(operationName = "CheckMaintainBundle", action = "http://sap.com/xi/A1S/Global/CustomerOrderProcessingManageCustomerOrderIn/CheckMaintainBundleRequest")
    @WebResult(name = "CustomerOrderRequestBundleCheckConfirmation_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerOrderRequestBundleCheckConfirmation_sync_V1")
    public CustomerOrderMaintainConfirmationBundleMessageSyncV1 checkMaintainBundle(
        @WebParam(partName = "CustomerOrderRequestBundleCheckRequest_sync_V1", name = "CustomerOrderRequestBundleCheckRequest_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
        CustomerOrderMaintainRequestBundleMessageSyncV1 customerOrderRequestBundleCheckRequestSyncV1
    ) throws StandardFaultMessage;
}
