
package com.sap.xi.a1s.global;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-18T14:25:31.271-03:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "StandardFaultMessage", targetNamespace = "http://sap.com/xi/AP/Common/Global")
public class StandardFaultMessage extends Exception {
    
    private com.sap.xi.ap.common.global.StandardFaultMessage standardFaultMessage;

    public StandardFaultMessage() {
        super();
    }
    
    public StandardFaultMessage(String message) {
        super(message);
    }
    
    public StandardFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public StandardFaultMessage(String message, com.sap.xi.ap.common.global.StandardFaultMessage standardFaultMessage) {
        super(message);
        this.standardFaultMessage = standardFaultMessage;
    }

    public StandardFaultMessage(String message, com.sap.xi.ap.common.global.StandardFaultMessage standardFaultMessage, Throwable cause) {
        super(message, cause);
        this.standardFaultMessage = standardFaultMessage;
    }

    public com.sap.xi.ap.common.global.StandardFaultMessage getFaultInfo() {
        return this.standardFaultMessage;
    }
}
